---
sudo: required
env:
  - distribution: centos
    version: 7


branches:
  only:
  - Testing

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'


      # Install requirements.
  # - sudo docker RUN yum -y install deltarpm epel-release initscripts 
  # - sudo docker run yum -y update
  # - sudo docker run yum -y install python-pip

      # Install Ansible via Pip.
  # - sudo docker RUN pip install ansible
script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":AnsibleSetup/roles/Splunk:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v AnsibleSetup/roles/Splunk/tests/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v AnsibleSetup/roles/Splunk/tests/test.yml'
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v AnsibleSetup/roles/Splunk/tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - 'sudo docker rm -f "$(cat ${container_id})"'

