---
# vars file for TeamCityAgent
teamcity_agent_server_url: 'teamcity.XYZ.com'
teamcity_agent_group: 'teamcity'
teamcity_agent_user: 'teamcity'
teamcity_agent_home: "/home/{{teamcity_agent_user}}/teamcity"
teamcity_agent_docker_group: 'docker'
