---
splunk_instance: 192.168.10.35:9997

splunk_user: "splunk"
splunk_group: "splunk"
splunk_uid: "10011"
splunk_gid: "10011"
splunk_release: "7.2.4.2"
splunk_url: "https://download.splunk.com/products/splunk/releases/{{ splunk_release }}/linux"
splunk_rpm_file: "splunk-7.2.4.2-fb30470262e3-linux-2.6-x86_64.rpm"
splunk_rpm: "{{ splunk_url }}/{{ splunk_rpm_file }}"
splunk_rpm_checksum: "md5:5b2df276acb22c3dd5f3f9245dfdc689"

splunk_admin_password: "Password1!"

splunk_indexer: "{{ splunk_instance }}"
splunk_index: "my-indexer-name"
