---
- name: "Create teamcity group: 'teamcity'"
  group:
    name: teamcity
    state: present
    system: yes

- name: "Create teamcity group: 'docker'"
  group:
    name: docker
    state: present
    system: yes

- name: "Create teamcity user:'teamcity'"
  user:
    name: teamcity
    groups: teamcity, docker
    state: present
    shell: /bin/bash
    createhome: yes
    system: yes
    home: /home/teamcity/teamcity

