---
# start of the splunk setup.
- name: Create Splunk group
  group:
    name: "{{ splunk_group }}"
    gid: "{{ splunk_gid }}"
    state: present
  tags: splunk_user

- name: Create Splunk user
  user:
    name: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    uid: "{{ splunk_uid }}"
    state: present
  tags: splunk_user

- name: Download the Splunk package
  get_url:
    url: "{{ splunk_rpm }}"
    dest: "/tmp/{{ splunk_rpm_file }}"

- name: Install Splunk
  become: yes
  become_user: root
  become_method: sudo
  yum:
    name: "/tmp/{{ splunk_rpm_file }}"
    state: present

- stat: path=/opt/splunk/etc/passwd
  register: passwd_created

- name: Create password file used by splunk as first user
  become: yes
  become_user: splunk
  when: passwd_created.stat.exists == False
  copy:
    dest: "/opt/splunk/etc/system/local/user-seed.conf"
    mode: 0600
    content: |
      [user_info]
      PASSWORD={{ splunk_admin_password }}

- name: Add inputs.config file
  template:
    src: inputs.conf
    dest: /opt/splunk/etc/system/local/inputs.conf
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    backup: yes

- name: Add indexes.conf
  become: yes
  become_user: splunk
  template:
    src: indexes.conf
    dest: /opt/splunk/etc/system/local/indexes.conf

- name: Add outputs.config file
  template:
    src: outputs.conf
    dest: /opt/splunk/etc/system/local/outputs.conf
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    backup: yes
  notify: Restart Splunk


- name: Create transforms.conf
  become: yes
  become_user: splunk
  register: transforms.conf
  template:
    src: transforms.conf
    dest: /opt/splunk/etc/system/local/transforms.conf
  notify: Restart Splunk

- name: Start Splunk Server
  become: yes
  become_user: splunk
  become_method: sudo
  shell: /opt/splunk/bin/splunk start --accept-license --answer-yes

# - name: Start Splunk Server
#   become: yes
#   become_user: splunk
#   become_method: sudo
#   shell: /opt/splunk/bin/splunk enable boot-start
#   notify: Restart Splunk