---
# start of the splunk setup.
- name: Create Splunk group
  group:
    name: "{{ splunk_group }}"
    gid: "{{ splunk_gid }}"
    state: present
  tags: splunk_user

- name: Create Splunk user
  user:
    name: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    uid: "{{ splunk_uid }}"
    state: present
  tags: splunk_user

- name: Download the Splunk package
  get_url:
    url: "{{ splunk_rpm }}"
    dest: "/tmp/{{ splunk_rpm_file }}"

- name: Install Splunk
  yum:
    name: "/tmp/{{ splunk_rpm_file }}"
    state: present

- stat: path=/opt/splunk/etc/passwd
  register: passwd_created

- name: Create passwd file
  become: yes
  become_user: splunk
  when: passwd_created.stat.exists == False
  copy:
    dest: "/opt/splunk/etc/system/local/user-seed.conf"
    mode: 0600
    content: |
      [user_info]
      PASSWORD={{ splunk_admin_password }}
- name: Copy inputs.config file
  template:
    src: inputz.conf
    dest: /opt/splunk/etc/system/local/inputs.conf
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    backup: yes

- name: Copy outputs.config file
  template:
    src: outputz.conf
    dest: /opt/splunk/etc/system/local/outputs.conf
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    backup: yes

- name: Installing splunk server
  become: yes
  become_user: splunk
  become_method: sudo
  shell: /opt/splunk/bin/splunk start --accept-license --answer-yes

# - name: Start splunk server
#   become: yes
#   become_user: splunk
#   become_method: sudo
#   shell: sudo systemctl start Splunkd
# End of the splunk forwarder setup.