---
# start of the splunk setup.
- name: Create splunkforwarder group
  group:
    name: "{{ splunk_group }}"
    gid: "{{ splunk_gid }}"
    state: present
  tags: splunk_user

- name: Create splunkforwarder user
  user:
    name: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    uid: "{{ splunk_uid }}"
    state: present
  tags: splunk_user

- name: Download the splunkforwarder package
  get_url:
    url: "{{ splunk_rpm }}"
    dest: "/tmp/{{ splunk_rpm_file }}"

- name: Install splunkforwarder
  become: yes
  become_user: root
  become_method: sudo
  yum:
    name: "/tmp/{{ splunk_rpm_file }}"
    state: present

- stat: path=/opt/splunkforwarder/etc/passwd
  register: passwd_created

- name: Create passwd file
  become: yes
  become_user: splunk
  when: passwd_created.stat.exists == False
  copy:
    dest: "/opt/splunkforwarder/etc/system/local/user-seed.conf"
    mode: 0600
    content: |
      [user_info]
      PASSWORD={{ splunk_admin_password }}
- name: Copy inputs.config file
  template:
    src: inputs.conf
    dest: /opt/splunkforwarder/etc/system/local/inputs.conf
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    backup: yes

- name: Copy outputs.config file
  template:
    src: outputs.conf
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    backup: yes

- name: Installing splunk server
  become: yes
  become_user: splunk
  become_method: sudo
  shell: /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes

# - name: Start splunk server
#   become: yes
#   become_user: splunk
#   become_method: 


#   shell: sudo systemctl start Splunkd
# End of the splunk forwarder setup.